config/routes.rb
Rails.application.routes.draw do
  resources :profits
  resources :stocks
  resources :charts
  resources :tickers
  resources :epss
  resources :yr_profits  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tickers#index"

  get "/list_profits_q1", to: 'profits#list_profits_q1'    
  get "/list_profits_q2", to: 'profits#list_profits_q2'    
  get "/list_profits_q3", to: 'profits#list_profits_q3'    
  get "/list_profits_q4", to: 'profits#list_profits_q4'     
  get "/list_tickers", to: 'tickers#list_tickers'    

end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :ticker
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:name, :market, :price, :max_price, :min_price, :pe, :pbv, :paid_up, :market_cap, :daily_volume, :beta, :ticker)
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :stock_name %>
  </div>

  <div class="field">
    <%= form.label :market %>
    <%= form.text_field :market, id: :stock_market %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :stock_price %>
  </div>

  <div class="field">
    <%= form.label :max_price %>
    <%= form.text_field :max_price, id: :stock_max_price %>
  </div>

  <div class="field">
    <%= form.label :min_price %>
    <%= form.text_field :min_price, id: :stock_min_price %>
  </div>

  <div class="field">
    <%= form.label :pe %>
    <%= form.text_field :pe, id: :stock_pe %>
  </div>

  <div class="field">
    <%= form.label :pbv %>
    <%= form.text_field :pbv, id: :stock_pbv %>
  </div>

  <div class="field">
    <%= form.label :paid_up %>
    <%= form.text_field :paid_up, id: :stock_paid_up %>
  </div>

  <div class="field">
    <%= form.label :market_cap %>
    <%= form.text_field :market_cap, id: :stock_market_cap %>
  </div>

  <div class="field">
    <%= form.label :daily_volume %>
    <%= form.text_field :daily_volume, id: :stock_daily_volume %>
  </div>

  <div class="field">
    <%= form.label :beta %>
    <%= form.text_field :beta, id: :stock_beta %>
  </div>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.number_field :ticker, id: :stock_ticker %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Stocks' %>
<h1>Stocks</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Market</th>
      <th>Price</th>
      <th>Max</th>
      <th>Min</th>
      <th>Pe</th>
      <th>Pbv</th>
      <th>Paid up</th>
      <th>Market cap</th>
      <th>Volume</th>
      <th>Beta</th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.name %></td>
        <td><%= stock.market %></td>
        <td><%= stock.price %></td>
        <td><%= stock.max_price %></td>
        <td><%= stock.min_price %></td>
        <td><%= stock.pe %></td>
        <td><%= stock.pbv %></td>
        <td><%= stock.paid_up %></td>
        <td><%= stock.market_cap %></td>
        <td><%= stock.daily_volume %></td>
        <td><%= stock.beta %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @stock.name %>
</p>

<p>
  <strong>Market:</strong>
  <%= @stock.market %>
</p>

<p>
  <strong>Price:</strong>
  <%= @stock.price %>
</p>

<p>
  <strong>Max price:</strong>
  <%= @stock.max_price %>
</p>

<p>
  <strong>Min price:</strong>
  <%= @stock.min_price %>
</p>

<p>
  <strong>Pe:</strong>
  <%= @stock.pe %>
</p>

<p>
  <strong>Pbv:</strong>
  <%= @stock.pbv %>
</p>

<p>
  <strong>Paid up:</strong>
  <%= @stock.paid_up %>
</p>

<p>
  <strong>Market cap:</strong>
  <%= @stock.market_cap %>
</p>

<p>
  <strong>Daily volume:</strong>
  <%= @stock.daily_volume %>
</p>

<p>
  <strong>Beta:</strong>
  <%= @stock.beta %>
</p>

<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>