config/routes.rb
Rails.application.routes.draw do
  resources :profits
  resources :stocks
  resources :charts
  resources :tickers
  resources :epss
  resources :yr_profits  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tickers#index"

  get "/list_profits_q1", to: 'profits#list_profits_q1'    
  get "/list_profits_q2", to: 'profits#list_profits_q2'    
  get "/list_profits_q3", to: 'profits#list_profits_q3'    
  get "/list_profits_q4", to: 'profits#list_profits_q4'     
  get "/list_tickers", to: 'tickers#list_tickers'    

end

app/models/chart.rb
class Chart < ApplicationRecord
	belongs_to :ticker
    default_scope { order(name: 'asc') }	
	before_save :assign_names

  	YEAR = [
			"2024",
			"2023",
			"2022",
			"2021",
			"2020",
			"2019",
      "2018",
      "2017",
			"2016",
			"2015",
			"2014",
			"2013"
        	]

  	QUARTER = [	  
			"3",
			"2",    		
			"1",     
			"4"
    ]

private

	def assign_names
		ticker = Ticker.find(self.ticker_id)
		self.name = ticker.name
  	end

end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update, :destroy]

  # GET /charts
  # GET /charts.json
  def index
    @charts = Chart.order('name asc, year desc, quarter desc')
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
  end

  # GET /charts/new
  def new
    @chart = Chart.new
  end

  # GET /charts/1/edit
  def edit
  end

  # POST /charts
  # POST /charts.json
  def create
    @chart = Chart.new(chart_params)

    respond_to do |format|
      if @chart.save
        format.html { redirect_to @chart, notice: 'Chart was successfully created.' }
        format.json { render :show, status: :created, location: @chart }
      else
        format.html { render :new }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charts/1
  # PATCH/PUT /charts/1.json
  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.html { redirect_to @chart, notice: 'Chart was successfully updated.' }
        format.json { render :show, status: :ok, location: @chart }
      else
        format.html { render :edit }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.json
  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to charts_url, notice: 'Chart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      @chart = Chart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chart_params
      params.require(:chart).permit(:ticker_id, :year, :quarter, :image_q, :image_y)
    end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= form_with(model: chart, local: true) do |form| %>
  <% if chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% chart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.collection_select :ticker_id, Ticker.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.select :year, Chart::YEAR, {} %>
  </div>

  <div class="field">
    <%= form.label :quarter %>
    <%= form.select :quarter, Chart::QUARTER, {} %>
  </div>

  <div class="field">
    <%= form.label :image_q %>
    <%= form.text_field :image_q, id: :chart_image_q %>
  </div>

  <div class="field">
    <%= form.label :image_y %>
    <%= form.text_field :image_y, id: :chart_image_y %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, 'Charts' %>
<h1>Charts</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Year</th>
      <th>Quarter</th>
      <th>Image q</th>
      <th>Image y</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charts.each do |chart| %>
      <tr>
        <td><%= chart.ticker.name %></td>
        <td><%= chart.year %></td>
        <td><%= chart.quarter %></td>
        <td><%= chart.image_q %></td>
        <td><%= chart.image_y %></td>
        <td><%= link_to 'Show', chart %></td>
        <td><%= link_to 'Edit', edit_chart_path(chart) %></td>
        <td><%= link_to 'Destroy', chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chart', new_chart_path %>

app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title, @chart.ticker.name + ' Chart' %>

<p>
  <strong>Ticker:</strong>
  <%= @chart.ticker.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @chart.year %>
</p>

<p>
  <strong>Quarter:</strong>
  <%= @chart.quarter %>
</p>

<!-- start of image quarter section -->
<div class="row">
  <div class="col-xs-12">
    <div class="card text-center text-white bg-dark">
      <div class="card-body"> 
            <%=  image_tag @chart.image_q, class: "card-img-top img-fluid"  %>
      </div> 
    </div> <!-- enf of card -->
  </div> <!-- end of col -->
</div> <!-- end of row -->
<!-- end of image quarter section -->
<br/>
<!-- start of image year section -->
<div class="row">
  <div class="col-xs-12">
    <div class="card text-center text-white bg-dark">
      <div class="card-body"> 
            <%=  image_tag @chart.image_y, class: "card-img-top img-fluid"  %>
      </div> 
    </div> <!-- enf of card -->
  </div> <!-- end of col -->
</div> <!-- end of row -->
<!-- end of image year section -->
<br/>
<%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %>