config/routes.rb
Rails.application.routes.draw do
  resources :profits
  resources :stocks
  resources :charts
  resources :tickers
  resources :epss
  resources :yr_profits  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "tickers#index"

  get "/list_profits_q1", to: 'profits#list_profits_q1'    
  get "/list_profits_q2", to: 'profits#list_profits_q2'    
  get "/list_profits_q3", to: 'profits#list_profits_q3'    
  get "/list_profits_q4", to: 'profits#list_profits_q4'     
  get "/list_tickers", to: 'tickers#list_tickers'    

end

app/models/profit.rb
class Profit < ApplicationRecord
  belongs_to :ticker
end

app/controllers/profits_controller.rb
class ProfitsController < ApplicationController
  before_action :set_profit, only: [:show, :edit, :update, :destroy]

  # GET /profits
  # GET /profits.json
  def index
    @profits = Profit.all
  end

  def list_profits_q1
      @profits = Profit.order(name: :asc)
  end

  def list_profits_q2
      @profits = Profit.where("publish_date >= '2018-07-01'").order(name: :asc, quarter: :desc)
  end

  def list_profits_q3
      @profits = Profit.where("publish_date >= '2022-10-01'").order(name: :asc, quarter: :desc)
  end
  def list_profits_q4
      @profits = Profit.where("publish_date >= '2023-01-01'").order(name: :asc, quarter: :desc)
  end

  # GET /profits/1
  # GET /profits/1.json
  def show
  end

  # GET /profits/new
  def new
    @profit = Profit.new
  end

  # GET /profits/1/edit
  def edit
  end

  # POST /profits
  # POST /profits.json
  def create
    @profit = Profit.new(profit_params)

    respond_to do |format|
      if @profit.save
        format.html { redirect_to @profit, notice: 'Profit was successfully created.' }
        format.json { render :show, status: :created, location: @profit }
      else
        format.html { render :new }
        format.json { render json: @profit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profits/1
  # PATCH/PUT /profits/1.json
  def update
    respond_to do |format|
      if @profit.update(profit_params)
        format.html { redirect_to @profit, notice: 'Profit was successfully updated.' }
        format.json { render :show, status: :ok, location: @profit }
      else
        format.html { render :edit }
        format.json { render json: @profit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profits/1
  # DELETE /profits/1.json
  def destroy
    @profit.destroy
    respond_to do |format|
      format.html { redirect_to profits_url, notice: 'Profit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profit
      @profit = Profit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profit_params
      params.require(:profit).permit(:name, :year, :quarter, :kind, :latest_amt_y, :previous_amt_y, :inc_amt_y, :inc_pct_y, :latest_amt_q, :previous_amt_q, :inc_amt_q, :inc_pct_q, :q_amt_c, :y_amt, :inc_amt_py, :inc_pct_py, :q_amt_p, :inc_amt_pq, :inc_pct_pq, :mean_pct, :std_pct, :publish_date, :ticker_id)
    end
end

app/helpers/profits_helper.rb
module ProfitsHelper

    def kind_desc(kind)
        case kind
        when 0
            kind_desc = 'Lower'            
        when 1
            kind_desc = 'Higher'          
        end     
    end

end

app/views/profits/_form.html.erb
<%= form_with(model: profit, local: true) do |form| %>
  <% if profit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profit.errors.count, "error") %> prohibited this profit from being saved:</h2>

      <ul>
      <% profit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :profit_name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :profit_year %>
  </div>

  <div class="field">
    <%= form.label :quarter %>
    <%= form.number_field :quarter, id: :profit_quarter %>
  </div>

  <div class="field">
    <%= form.label :kind %>
    <%= form.number_field :kind, id: :profit_kind %>
  </div>

  <div class="field">
    <%= form.label :latest_amt_y %>
    <%= form.number_field :latest_amt_y, id: :profit_latest_amt_y %>
  </div>

  <div class="field">
    <%= form.label :previous_amt_y %>
    <%= form.number_field :previous_amt_y, id: :profit_previous_amt_y %>
  </div>

  <div class="field">
    <%= form.label :inc_amt_y %>
    <%= form.number_field :inc_amt_y, id: :profit_inc_amt_y %>
  </div>

  <div class="field">
    <%= form.label :inc_pct_y %>
    <%= form.text_field :inc_pct_y, id: :profit_inc_pct_y %>
  </div>

  <div class="field">
    <%= form.label :latest_amt_q %>
    <%= form.number_field :latest_amt_q, id: :profit_latest_amt_q %>
  </div>

  <div class="field">
    <%= form.label :previous_amt_q %>
    <%= form.number_field :previous_amt_q, id: :profit_previous_amt_q %>
  </div>

  <div class="field">
    <%= form.label :inc_amt_q %>
    <%= form.number_field :inc_amt_q, id: :profit_inc_amt_q %>
  </div>

  <div class="field">
    <%= form.label :inc_pct_q %>
    <%= form.text_field :inc_pct_q, id: :profit_inc_pct_q %>
  </div>

  <div class="field">
    <%= form.label :q_amt_c %>
    <%= form.number_field :q_amt_c, id: :profit_q_amt_c %>
  </div>

  <div class="field">
    <%= form.label :y_amt %>
    <%= form.number_field :y_amt, id: :profit_y_amt %>
  </div>

  <div class="field">
    <%= form.label :inc_amt_py %>
    <%= form.number_field :inc_amt_py, id: :profit_inc_amt_py %>
  </div>

  <div class="field">
    <%= form.label :inc_pct_py %>
    <%= form.text_field :inc_pct_py, id: :profit_inc_pct_py %>
  </div>

  <div class="field">
    <%= form.label :q_amt_p %>
    <%= form.number_field :q_amt_p, id: :profit_q_amt_p %>
  </div>

  <div class="field">
    <%= form.label :inc_amt_pq %>
    <%= form.number_field :inc_amt_pq, id: :profit_inc_amt_pq %>
  </div>

  <div class="field">
    <%= form.label :inc_pct_pq %>
    <%= form.text_field :inc_pct_pq, id: :profit_inc_pct_pq %>
  </div>

  <div class="field">
    <%= form.label :mean_pct %>
    <%= form.text_field :mean_pct, id: :profit_mean_pct %>
  </div>

  <div class="field">
    <%= form.label :std_pct %>
    <%= form.text_field :std_pct, id: :profit_std_pct %>
  </div>

  <div class="field">
    <%= form.label :publish_date %>
    <%= form.date_select :publish_date, id: :profit_publish_date %>
  </div>

  <div class="field">
    <%= form.label :ticker_id %>
    <%= form.text_field :ticker_id, id: :profit_ticker_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/profits/edit.html.erb
<h1>Editing Profit</h1>

<%= render 'form', profit: @profit %>

<%= link_to 'Show', @profit %> |
<%= link_to 'Back', profits_path %>

app/views/profits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profits</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Quarter</th>
      <th>Kind</th>
      <th>Latest amt y</th>
      <th>Previous amt y</th>
      <th>Inc amt y</th>
      <th>Inc pct y</th>
      <th>Latest amt q</th>
      <th>Previous amt q</th>
      <th>Inc amt q</th>
      <th>Inc pct q</th>
      <th>Q amt c</th>
      <th>Y amt</th>
      <th>Inc amt py</th>
      <th>Inc pct py</th>
      <th>Q amt p</th>
      <th>Inc amt pq</th>
      <th>Inc pct pq</th>
      <th>Mean pct</th>
      <th>Std pct</th>
      <th>Publish date</th>
      <th>Ticker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profits.each do |profit| %>
      <tr>
        <td><%= profit.name %></td>
        <td><%= profit.year %></td>
        <td><%= profit.quarter %></td>
        <td><%= profit.kind %></td>
        <td><%= profit.latest_amt_y %></td>
        <td><%= profit.previous_amt_y %></td>
        <td><%= profit.inc_amt_y %></td>
        <td><%= profit.inc_pct_y %></td>
        <td><%= profit.latest_amt_q %></td>
        <td><%= profit.previous_amt_q %></td>
        <td><%= profit.inc_amt_q %></td>
        <td><%= profit.inc_pct_q %></td>
        <td><%= profit.q_amt_c %></td>
        <td><%= profit.y_amt %></td>
        <td><%= profit.inc_amt_py %></td>
        <td><%= profit.inc_pct_py %></td>
        <td><%= profit.q_amt_p %></td>
        <td><%= profit.inc_amt_pq %></td>
        <td><%= profit.inc_pct_pq %></td>
        <td><%= profit.mean_pct %></td>
        <td><%= profit.std_pct %></td>
        <td><%= profit.publish_date %></td>
        <td><%= profit.ticker %></td>
        <td><%= link_to 'Show', profit %></td>
        <td><%= link_to 'Edit', edit_profit_path(profit) %></td>
        <td><%= link_to 'Destroy', profit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profit', new_profit_path %>

app/views/profits/list_profits_q1.html.erb
<h1>Profits Q1</h1>
<div class="row">
    <div class="col-xs-3 col-sm-1 alignC">
    </div> <!-- end of col1 -->
    <div class="col-xs-3 col-sm-2 alignR">
        <%= '18Q1-17Q2' %><br/>
        <%= '--ditto--' %><br/>
        <%= ' 2018 Q1 ' %><br/>
        <%= '--ditto--' %>
    </div> <!-- end of col2 -->
    <div class="col-xs-3 col-sm-2 alignR">
        <%= '17Q1-16Q2' %><br/>
        <%= '17Q4-17Q1' %><br/>
        <%= ' 2017 Q1 ' %><br/>
        <%= ' 2017 Q4 ' %>        
    </div> <!-- end of col3 -->
    <div class="col-xs-3 col-sm-1 alignR">
        <%= 'Inc./' %><br/>
        <%= 'Dec.' %><br/>
        <%= 'Profit' %><br/>
        <%= 'Amt' %>
    </div> <!-- end of col4 -->
    <div class="col-xs-2 col-sm-1 alignR">
        <%= 'Inc./' %><br/>
        <%= 'Dec.' %><br/>
        <%= 'Profit' %><br/>
        <%= 'Pct' %>
    </div> <!-- end of col5 -->
    <div class="col-xs-2 col-sm-1 alignR">
        <%= 'Max./' %><br/>
        <%= 'Min.' %><br/>
        <%= 'Price' %><br/>
        <%= '52-w' %>
    </div> <!-- end of col6 -->
    <div class="col-xs-2 col-sm-2 alignR">
       <%= 'IAA' %><br/>
        <%= 'Buy' %><br/>
        <%= 'Hold' %><br/>
        <%= 'Sell' %>
    </div> <!-- end of col7 -->
    <div class="col-xs-2 col-sm-1 alignR">
    </div> <!-- end of col8 -->
    <div class="col-xs-4 col-sm-1 alignR">
        <%= 'Sales' %><br/>
        <%= 'Amt' %><br/>
        <%= 'in' %><br/>
        <%= 'mil.' %>
    </div> <!-- end of col9 -->
</div> <!-- end of header row -->
<% yesterday = Date.today - 1 %>
<% msg = '-'*20 + ' Data as end of ' + Date.yesterday.strftime("%b-%d ") + '-'*20 %>

<footer> <!-- start of cut -->
<p align="Center"><%= msg %></p>
<!-- start of loop -->
<% @profits.each do |profit| %>
    <div class="row">

        <div class="col-xs-3 col-sm-1 alignC">
            <b><%= profit.name %></b><br/>
            <%= profit.year %><br/>
            <%= profit.quarter %><br/>
            <%= kind_desc(profit.kind) %>
        </div>

        <div class="col-xs-3 col-sm-2 alignR">
            <%= number_with_precision(profit.latest_amt_y, precision: 0, delimiter: ",") %><br/><br/>
            <%= number_with_precision(profit.q_amt_c, precision: 0, delimiter: ",") %>
        </div>

        <div class="col-xs-3 col-sm-2 alignR">
            <%= number_with_precision(profit.previous_amt_y, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.previous_amt_q, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.y_amt, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.q_amt_p, precision: 0, delimiter: ",") %>
        </div>

        <div class="col-xs-3 col-sm-1 alignR">
            <%= number_with_precision(profit.inc_amt_y, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.inc_amt_q, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.inc_amt_py, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.inc_amt_pq, precision: 0, delimiter: ",") %>
        </div>

        <div class="col-xs-2 col-sm-1 alignR">
            <%= number_to_percentage(profit.inc_pct_y, precision: 2, delimiter: ",") %><br/>
            <%= number_to_percentage(profit.inc_pct_q, precision: 2, delimiter: ",") %><br/>
            <%= number_to_percentage(profit.inc_pct_py, precision: 2, delimiter: ",") %><br/>
            <%= number_to_percentage(profit.inc_pct_pq, precision: 2, delimiter: ",") %>
        </div>

        <div class="col-xs-2 col-sm-1 alignR">
            <%= 'Max' %><br/>
            <%= number_with_precision(profit.ticker.stock.max_price, precision: 2, delimiter: ",") %><br/>
            <%= 'Min' %><br/>
            <%= number_with_precision(profit.ticker.stock.min_price, precision: 2, delimiter: ",") %>
        </div>

        <div class="col-xs-2 col-sm-2 alignR">
            <%= 'Target' %><br/>
            <% if profit.ticker.consensu %>
                <%= number_with_precision(profit.ticker.consensu.target_price, precision: 2, delimiter: ",") %><br/>
                <%= 'B-H-S' %><br/>
                <%= profit.ticker.consensu.bhs %>
            <% end %>
        </div>

        <div class="col-xs-2 col-sm-1 alignR">
            <%= 'P/E' %><br/>
            <%= number_with_precision(profit.ticker.stock.pe, precision: 2, delimiter: ",") %><br/>
            <%= 'P/BV' %><br/>
            <%= number_with_precision(profit.ticker.stock.pbv, precision: 2, delimiter: ",") %>
        </div>

        <div class="col-xs-4 col-sm-1 alignR">
            <%= 'Volume' %><br/>
            <%= number_with_precision(profit.ticker.stock.daily_volume, precision: 2, delimiter: ",") %><br/>
            <%= 'Beta' %><br/>
            <%= number_with_precision(profit.ticker.stock.beta, precision: 2, delimiter: ",") %>
        </div>

    </div> <!-- end of row -->
    <br/>
<% end %>
<!-- end of loop -->
<% msg = '-'*50 %>
<p align="Center"><%= msg %></p>
</footer> <!-- end of cut -->

app/views/profits/list_profits_q2.html.erb
<h1>Profits Q2</h1>
<div class="row">
    <div class="col-xs-3 col-sm-1 alignC">
    </div> <!-- end of col1 -->
    <div class="col-xs-3 col-sm-2 alignR">
        <%= '18Q2-17Q3' %><br/>
        <%= '--ditto--' %><br/>
        <%= ' 2018 Q2 ' %><br/>
        <%= '--ditto--' %>
    </div> <!-- end of col2 -->
    <div class="col-xs-3 col-sm-2 alignR">
        <%= '17Q2-16Q3' %><br/>
        <%= '18Q1-17Q2' %><br/>
        <%= ' 2017 Q2 ' %><br/>
        <%= ' 2018 Q1 ' %>        
    </div> <!-- end of col3 -->
    <div class="col-xs-3 col-sm-1 alignR">
        <%= 'Inc./' %><br/>
        <%= 'Dec.' %><br/>
        <%= 'Profit' %><br/>
        <%= 'Amt' %>
    </div> <!-- end of col4 -->
    <div class="col-xs-2 col-sm-1 alignR">
        <%= 'Inc./' %><br/>
        <%= 'Dec.' %><br/>
        <%= 'Profit' %><br/>
        <%= 'Pct' %>
    </div> <!-- end of col5 -->
    <div class="col-xs-2 col-sm-1 alignR">
        <%= 'Max./' %><br/>
        <%= 'Min.' %><br/>
        <%= 'Price' %><br/>
        <%= '52-w' %>
    </div> <!-- end of col6 -->
    <div class="col-xs-2 col-sm-2 alignR">
       <%= 'IAA' %><br/>
        <%= 'Buy' %><br/>
        <%= 'Hold' %><br/>
        <%= 'Sell' %>
    </div> <!-- end of col7 -->
    <div class="col-xs-2 col-sm-1 alignR">
    </div> <!-- end of col8 -->
    <div class="col-xs-4 col-sm-1 alignR">
        <%= 'Sales' %><br/>
        <%= 'Amt' %><br/>
        <%= 'in' %><br/>
        <%= 'mil.' %>
    </div> <!-- end of col9 -->
</div> <!-- end of header row -->
<% yesterday = Date.today - 1 %>
<% msg = '-'*20 + ' Data as end of ' + Date.yesterday.strftime("%b-%d ") + '-'*20 %>

<footer> <!-- start of cut -->
<p align="Center"><%= msg %></p>
<!-- start of loop -->
<% @profits.each do |profit| %>
    <div class="row">

        <div class="col-xs-3 col-sm-1 alignC">
            <b><%= profit.name %></b><br/>
            <%= profit.year %><br/>
            <%= profit.quarter %><br/>
            <%= kind_desc(profit.kind) %>
        </div>

        <div class="col-xs-3 col-sm-2 alignR">
            <%= number_with_precision(profit.latest_amt_y, precision: 0, delimiter: ",") %><br/><br/>
            <%= number_with_precision(profit.q_amt_c, precision: 0, delimiter: ",") %>
        </div>

        <div class="col-xs-3 col-sm-2 alignR">
            <%= number_with_precision(profit.previous_amt_y, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.previous_amt_q, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.y_amt, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.q_amt_p, precision: 0, delimiter: ",") %>
        </div>

        <div class="col-xs-3 col-sm-1 alignR">
            <%= number_with_precision(profit.inc_amt_y, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.inc_amt_q, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.inc_amt_py, precision: 0, delimiter: ",") %><br/>
            <%= number_with_precision(profit.inc_amt_pq, precision: 0, delimiter: ",") %>
        </div>

        <div class="col-xs-2 col-sm-1 alignR">
            <%= number_to_percentage(profit.inc_pct_y, precision: 2, delimiter: ",") %><br/>
            <%= number_to_percentage(profit.inc_pct_q, precision: 2, delimiter: ",") %><br/>
            <%= number_to_percentage(profit.inc_pct_py, precision: 2, delimiter: ",") %><br/>
            <%= number_to_percentage(profit.inc_pct_pq, precision: 2, delimiter: ",") %>
        </div>

        <div class="col-xs-2 col-sm-1 alignR">
            <%= 'Max' %><br/>
            <%= number_with_precision(profit.ticker.stock.max_price, precision: 2, delimiter: ",") %><br/>
            <%= 'Min' %><br/>
            <%= number_with_precision(profit.ticker.stock.min_price, precision: 2, delimiter: ",") %>
        </div>

        <div class="col-xs-2 col-sm-2 alignR">
            <%= 'Target' %><br/>
            <% if profit.ticker.consensu %>
                <%= number_with_precision(profit.ticker.consensu.target_price, precision: 2, delimiter: ",") %><br/>
                <%= 'B-H-S' %><br/>
                <%= profit.ticker.consensu.bhs %>
            <% end %>
        </div>

        <div class="col-xs-2 col-sm-1 alignR">
            <%= 'P/E' %><br/>
            <%= number_with_precision(profit.ticker.stock.pe, precision: 2, delimiter: ",") %><br/>
            <%= 'P/BV' %><br/>
            <%= number_with_precision(profit.ticker.stock.pbv, precision: 2, delimiter: ",") %>
        </div>

        <div class="col-xs-4 col-sm-1 alignR">
            <%= 'Volume' %><br/>
            <%= number_with_precision(profit.ticker.stock.daily_volume, precision: 2, delimiter: ",") %><br/>
            <%= 'Beta' %><br/>
            <%= number_with_precision(profit.ticker.stock.beta, precision: 2, delimiter: ",") %>
        </div>

    </div> <!-- end of row -->
    <br/>
<% end %>
<!-- end of loop -->
<% msg = '-'*50 %>
<p align="Center"><%= msg %></p>
</footer> <!-- end of cut -->

app/views/profits/new.html.erb
<h1>New Profit</h1>

<%= render 'form', profit: @profit %>

<%= link_to 'Back', profits_path %>

app/views/profits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profit.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @profit.year %>
</p>

<p>
  <strong>Quarter:</strong>
  <%= @profit.quarter %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @profit.kind %>
</p>

<p>
  <strong>Latest amt y:</strong>
  <%= @profit.latest_amt_y %>
</p>

<p>
  <strong>Previous amt y:</strong>
  <%= @profit.previous_amt_y %>
</p>

<p>
  <strong>Inc amt y:</strong>
  <%= @profit.inc_amt_y %>
</p>

<p>
  <strong>Inc pct y:</strong>
  <%= @profit.inc_pct_y %>
</p>

<p>
  <strong>Latest amt q:</strong>
  <%= @profit.latest_amt_q %>
</p>

<p>
  <strong>Previous amt q:</strong>
  <%= @profit.previous_amt_q %>
</p>

<p>
  <strong>Inc amt q:</strong>
  <%= @profit.inc_amt_q %>
</p>

<p>
  <strong>Inc pct q:</strong>
  <%= @profit.inc_pct_q %>
</p>

<p>
  <strong>Q amt c:</strong>
  <%= @profit.q_amt_c %>
</p>

<p>
  <strong>Y amt:</strong>
  <%= @profit.y_amt %>
</p>

<p>
  <strong>Inc amt py:</strong>
  <%= @profit.inc_amt_py %>
</p>

<p>
  <strong>Inc pct py:</strong>
  <%= @profit.inc_pct_py %>
</p>

<p>
  <strong>Q amt p:</strong>
  <%= @profit.q_amt_p %>
</p>

<p>
  <strong>Inc amt pq:</strong>
  <%= @profit.inc_amt_pq %>
</p>

<p>
  <strong>Inc pct pq:</strong>
  <%= @profit.inc_pct_pq %>
</p>

<p>
  <strong>Mean pct:</strong>
  <%= @profit.mean_pct %>
</p>

<p>
  <strong>Std pct:</strong>
  <%= @profit.std_pct %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @profit.publish_date %>
</p>

<p>
  <strong>Ticker:</strong>
  <%= @profit.ticker %>
</p>

<%= link_to 'Edit', edit_profit_path(@profit) %> |
<%= link_to 'Back', profits_path %>